VidlyPrototype/Controllers/LanguagesController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace VidlyPrototype.Controllers
{
    public class LanguagesController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Change(string LanguageAbbreviation)
        {
            if(LanguageAbbreviation != null)
            {
                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(LanguageAbbreviation);
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(LanguageAbbreviation);

            }

            HttpCookie cookie = new HttpCookie("Language");
            cookie.Value = LanguageAbbreviation;
            Response.Cookies.Add(cookie);

            return RedirectToAction("Index", "Home");
        }
    }
}

VidlyPrototype/Views/Languages/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="mt-5">
    <div class="py-1">
        <div class="row">
            <div class="col-md-5">
                <div class="px-3">
                    <div class="card">
                        <div class="card-body">
                            <ul class="list-group">
                                <li class="list-group-item">
                                    @Html.ActionLink("English", "Change", "Languages", new { LanguageAbbreviation = "en" }, null)
                                </li>
                                <li class="list-group-item">
                                    @Html.ActionLink("Turkish", "Change", "Languages", new { LanguageAbbreviation = "tr" }, null)
                                </li>
                                <li class="list-group-item">
                                    @DateTime.Now.ToString()
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>